# Site settings
title: Stewart Dulaney
description: 'Software developer in Los Angeles'
url: 'https://www.stewartdulaney.com'
baseurl: '/'
google_analytics: 'UA-76143550-1'
disqus_shortname: 'www-stewartdulaney-com'

author:
  name: 'Stewart Dulaney'
  email: stewart@stewartdulaney.com
  twitter_username:
  facebook_username:
  github_username:  sdulaney
  linkedin_username:  stewartdulaney

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png', '_site' ]

# deployment
host: 127.0.0.1
port: 5000
